version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    restart: always
    tty: true
    stdin_open: true
    command: 'bash entrypoint.sh'
