/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * (title)
 * A sample service
 * OpenAPI spec version: 1.0
 */

export interface SignUpInput {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  birthday?: string;
  frontIdentification?: Blob;
  backIdentification?: Blob;
}
