/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * (title)
 * A sample service
 * OpenAPI spec version: 1.0
 */
import type { SignUpValidationError } from './signUpValidationError';

export interface SignUpValidationErrorResponse {
  code: number;
  errors: SignUpValidationError;
}
